services:

  database:
    build: ./database
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    external: true